### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by YzY229** [Sam-DevZ/Discord-RoleReact#10]
The roles aren't adding nor removing due to errors

**Comment by Addoie** [comment]
The code is deprecated therefore meaning that you need to find the newly updates code this can be found at https://discord.js.org

**Comment by EugenioYT** [comment]
Can someone tell me what is deprecated?

**Comment by ipadpuppydogdude1** [comment]
The code is fine. I have contributed to it once and fixed a general deprivation
