### ISSUE TITLE
Rich embed

### ISSUE THREAD

**Issue by Sikksens** [Sam-DevZ/Discord-RoleReact#14]
Hey

Would it be possible to have the Roles listed in a Rich embed with their Emoji's next to them for reference then have the reactions list below the embed?

I was thinking maybe something like this?
![discord_2019-02-08_14-48-41](https://user-images.githubusercontent.com/15923337/52479282-c3c1b080-2bb0-11e9-8e2d-880f1a55eec2.png)

**Comment by Sam-DevZ** [comment]
This looks amazing. I'll look into it!

**Comment by Sam-DevZ** [comment]
Closing this since it's been added.
