### ISSUE TITLE
include thumnail option ?

### ISSUE THREAD

**Issue by maddyrien** [Sam-DevZ/Discord-RoleReact#16]
Thank you for providing your code, my own bot was causing me ends of headaches.  I was hopeing you might consider in your next version though, to include thumnails as embeds generally allow, and or a theird option to true/fales, allowing for an imbed image to be sent instead of a rich embed. 

Thank you again.

**Comment by acollierr17** [comment]
Hey! I can add this in a new PR in the near future. I'll probably have a configurable option where the embed thumbnail can be toggled with another option to provide the link to the thumbnail.

**Comment by maddyrien** [comment]
Thank you very much !
