### ISSUE TITLE
embed error?

### ISSUE THREAD

**Issue by TheFrodoDE** [Sam-DevZ/Discord-RoleReact#17]
![54231](https://user-images.githubusercontent.com/36931450/54494417-5c4aff00-48da-11e9-9e24-8271a70528cb.png)
If i make an emote like :overwatch: on my Discord Server on the embed wont show up the emote. Please Help. (Sorry for my bad englisch)

**Comment by JohnyMuffin** [comment]
I don't believe bots support getting Custom Server Emojis straight away, i believe you will need to change some of the code.
Here is an example with NodeJS how to get custom Emojis
https://anidiots.guide/coding-guides/using-emojis
It also looks like you can use the Emojis ID to directly react, although i have never done this.
message.react([emoji_id])

I have never used Reactions in Nodejs, but hopefully that is helpful.

**Comment by acollierr17** [comment]
Hey, as @JohnyMuffin said, there isn't support for custom emojis out of the box with this script. However, I can address this matter in the near future with a new PR as I know how to address this. So keep an eye out for that!

**Comment by acollierr17** [comment]
This has been resolved in the recent pull request. @Sam-DevZ, can you resolve this issue?
