### ISSUE TITLE
Emoji personalised

### ISSUE THREAD

**Issue by Firesn4ke** [Sam-DevZ/Discord-RoleReact#19]
If I associate with the custom emoji code everything works fine but does not associate the role to the person

**Comment by acollierr17** [comment]
Hey, can you show some examples of the issue you're having? It'll be easier to debug.

**Comment by acollierr17** [comment]
Hello, I was able to reproduce this issue. I am currently investigating a fix for it.

**Comment by acollierr17** [comment]
This has been resolved in the recent PR (#27). Closed.
