### ISSUE TITLE
Idk why but my bot is busted

### ISSUE THREAD

**Issue by xPharaoHx** [Sam-DevZ/Discord-RoleReact#20]
Heres the error I get when clicking a rank. It used to work, then just broke for no reason.

(node:3048) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Users\Rayce\Desktop\Pugbot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:79:15)
    at then (C:\Users\Rayce\Desktop\Pugbot\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xPharaoHx** [comment]
Fixed it, accidentally removed perms from bot.

**Comment by acollierr17** [comment]
@Sam-DevZ Can you close this issue and the other ones that need to be closed? There's about 4-5 other issues that need to be closed and old PRs that are open.

**Comment by Sam-DevZ** [comment]
Closed.
