### ISSUE TITLE
cant figure this out

### ISSUE THREAD

**Issue by StudNastty** [Sam-DevZ/Discord-RoleReact#25]
Unhandled Rejection: 

 TypeError: Cannot read property 'fields' of undefined

**Comment by acollierr17** [comment]
Can you leave more details on what you did to reach that error?

**Comment by StudNastty** [comment]
I believe i have fixed it already i will check later if its resolved

**Comment by acollierr17** [comment]
I was actually able to reproduce the issue you were having, so I will be further investigating it. Thanks for reporting this issue.

**Comment by acollierr17** [comment]
This has been resolved in the recent PR (#27). Closed.
