### ISSUE TITLE
Combine messages

### ISSUE THREAD

**Issue by Kurokiriowo** [Sam-DevZ/Discord-RoleReact#3]
I have a lot of roles that I put into the settings at the top. I was wondering if there was a way to post one single message with all the roles instead of one message for each role?

**Comment by SM-Wistful** [comment]
Hi,

If the bot creates one message, then all of the reactions will appear the bottom of the message. In my opinion this is less intuitive. How many roles do you have? Could you provide a screenshot showing where it becomes unmanageable? It's not out of the question to add a feature where, if there are > X roles, a single message is used.

**Comment by ipadpuppydogdude1** [comment]
You can try to do it yourself, or I can try it. DM me at ipadpuppydogdude1#3562 and I will get back to you.

**Comment by acollierr17** [comment]
This feature is possible with the embed system. You can read more information in the [README](https://github.com/Sam-DevZ/Discord-RoleReact/blob/master/README.md) file.
