### ISSUE TITLE
Running multiple instances with same prefix

### ISSUE THREAD

**Issue by cwchristerw** [Sam-DevZ/Discord-RoleReact#30]
**Describe the bug**
I have used as my setupCMD, they all start with same `rr!createrolemessage` but have whitespace and then after some keyword. It should show different but now it will show all different even when they are meant to be on different channels.
`rr!createrolemessage doer`
`rr!createrolemessage games`
`rr!createrolemessage consoles`

**To Reproduce**
1. Create configs for multiple bots with same botToken and put first setupCMD: "rr!createrolemessage consoles" and second setupCMD: "rr!createrolemessage games"
2. Start different bot instances
3. Type different setupCMD to different Discord channels.

**Expected behavior**
It should take full command and shouldnt show anything when typing just "rr!createrolemessage" when setupCMD has whitespace

**Additional context**

---

If you want to implement a fix for this bug, please open a draft pull request which references this issue.

**Comment by cwchristerw** [comment]
Newer mind you can close this because it considers `rr!createrolemessage` and `doer` as different commands because there is whitespace

**Comment by cwchristerw** [comment]
actually this ended up also in to other kind of bug

**Comment by acollierr17** [comment]
The current state of the bot is not made to accept multiple embeds. There is PR #28 which does plan on implementing the former, but that is still under review. 

In your previous comment, you mentioned there was a bug. If you could create a new issue and go more in-depth, that would be great.
