### ISSUE TITLE
.

### ISSUE THREAD

**Issue by AMr404** [Sam-DevZ/Discord-RoleReact#4]
ho to do reactions in one line?

**Comment by SM-Wistful** [comment]
Are you asking how to have the bot send all of the information in one message? It's not currently possible, but I've been thinking about adding it.

**Comment by Chacha-dooo** [comment]
I hope you will implement this feature, it would be really great!

**Comment by acollierr17** [comment]
This feature is possible with the embed system. You can read more information in the [README](https://github.com/Sam-DevZ/Discord-RoleReact/blob/master/README.md) file.
